/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "broadcast_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(broadcast_message_header, broadcast_message_header, AUTO)


PB_BIND(broadcast_message_payload, broadcast_message_payload, AUTO)




